// Generated by gencpp from file fork_msg/LppCmd.msg
// DO NOT EDIT!


#ifndef FORK_MSG_MESSAGE_LPPCMD_H
#define FORK_MSG_MESSAGE_LPPCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace fork_msg
{
template <class ContainerAllocator>
struct LppCmd_
{
  typedef LppCmd_<ContainerAllocator> Type;

  LppCmd_()
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , kapp(0.0)
    , velocity(0.0)  {
    }
  LppCmd_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , yaw(0.0)
    , kapp(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef float _kapp_type;
  _kapp_type kapp;

   typedef float _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::fork_msg::LppCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::fork_msg::LppCmd_<ContainerAllocator> const> ConstPtr;

}; // struct LppCmd_

typedef ::fork_msg::LppCmd_<std::allocator<void> > LppCmd;

typedef boost::shared_ptr< ::fork_msg::LppCmd > LppCmdPtr;
typedef boost::shared_ptr< ::fork_msg::LppCmd const> LppCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::fork_msg::LppCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::fork_msg::LppCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::fork_msg::LppCmd_<ContainerAllocator1> & lhs, const ::fork_msg::LppCmd_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.yaw == rhs.yaw &&
    lhs.kapp == rhs.kapp &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::fork_msg::LppCmd_<ContainerAllocator1> & lhs, const ::fork_msg::LppCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace fork_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::fork_msg::LppCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::fork_msg::LppCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fork_msg::LppCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::fork_msg::LppCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fork_msg::LppCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::fork_msg::LppCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::fork_msg::LppCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a52144db59699080735120a4546b01e6";
  }

  static const char* value(const ::fork_msg::LppCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa52144db59699080ULL;
  static const uint64_t static_value2 = 0x735120a4546b01e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::fork_msg::LppCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fork_msg/LppCmd";
  }

  static const char* value(const ::fork_msg::LppCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::fork_msg::LppCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 yaw\n"
"float32 kapp\n"
"float32 velocity\n"
;
  }

  static const char* value(const ::fork_msg::LppCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::fork_msg::LppCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.yaw);
      stream.next(m.kapp);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LppCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::fork_msg::LppCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::fork_msg::LppCmd_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "kapp: ";
    Printer<float>::stream(s, indent + "  ", v.kapp);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FORK_MSG_MESSAGE_LPPCMD_H
